### ISSUE TITLE
Guidance about upgrading out of this

### ISSUE THREAD

**Issue by Sylk** [jamielsharief/docker-mysql#4]
I don't have an M1 processor, and thus can't test if mysql/mysql-server:8.0 works on m1. But I haven't seen any updates to this, and was just curious what would need to be done so that I can use the default docker container instead of this one?

We currently have a team with m1's and intel processors.

**Comment by jamielsharief** [comment]
This repo is the source code for building the docker image, the docker image is built daily, which you can see https://hub.docker.com/r/jamielsharief/mysql which is handled by the github actions. IMO, there is not really anything that needs to be modified in this package at this time, since the folks at MySQL are doing the hard work.

The only sort of difference here is the `mysql_native_password` plugin, in my package, this enabled by default, so you would need to configure docker to enable this if you use the mysql package.

You could use something like this in your `docker-compose.yml`
```
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - db
    links:
      - "db"
  db:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
 volumes:
   mysql-data:
```
